name: alafasynasheed
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  just_audio_background: ^0.0.1-beta.9
  permission_handler: ^10.2.0
  dio: ^4.0.6
  just_audio: ^0.9.31
  provider:
  path_provider: ^2.0.12
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0


flutter_icons:
  android: treu
  ios: true
  image_path: "asset/alafasy.jpg"
  min_sdk_android: 21



flutter:

  uses-material-design: true
  assets:
    - asset/

